### PR TITLE
Added class templates 

### PR DESCRIPTION
**Pull request by samuel-watson**
I've added class templates so that the classes will be compatible with armadillo and Eigen vectors as well as std::vectors, in case they're needed. Are you happy for me to submit to cran?

### CODE REVIEW

**Comment by ypan1988** [comment]
Sure. Feel free to submit it to CRAN by yourself.

**Comment by samuel-watson** [comment]
Thanks Yi. I noticed an error (missing header for algorithm) so will update and submit as new version

**Comment by ypan1988** [comment]
Hi, @samuel-watson. I noticed that you have not updated the package on CRAN. Are you able to submit it? Or as I am the maintainer, I need to do something so that you can become the new maintainer?

**Comment by samuel-watson** [comment]
Hi @ypan1988 I have submitted it today, so I think it has sent you an email as maintainer to confirm. When you've accepted then I will submit another package that depends on it.

**Comment by ypan1988** [comment]
@samuel-watson sorry for the delay, it is done.

**Pull request merged**
